# Використовуємо офіційний образ Golang як базовий для збірки
FROM golang:1.24 AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download
RUN go mod verify

COPY . .

ENV INTEGRATION_TEST=true

ENTRYPOINT ["go", "test", "-v", "-count=1", "./integration/..."]
